import {Raleway} from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

const RaleWay = Raleway({
    subsets: ["latin"]
})

export const metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${RaleWay.className} antialiased`}>
        <Navbar/>
        {children}
        <Footer/>
        </body>
        </html>
    );
}
